# SOL1
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER='W' AND TLNO IS NOT NULL AND MONTH(DATE_OF_BIRTH)=3
ORDER BY MEMBER_ID

# SOL2
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_FORMAT
FROM MEMBER_PROFILE
WHERE DATE_OF_BIRTH LIKE "%%%%-03%" AND GENDER='W' AND TLNO IS NOT NULL
ORDER BY MEMBER_ID