SELECT A.FLAVOR
FROM FIRST_HALF A JOIN
        (SELECT FLAVOR
        FROM ICECREAM_INFO
        WHERE INGREDIENT_TYPE LIKE 'fruit%') B
      ON A.FLAVOR = B.FLAVOR
WHERE A.TOTAL_ORDER > 3000
ORDER BY TOTAL_ORDER DESC